### ISSUE TITLE
Logging in doesn't work

### ISSUE THREAD

**Issue by GeorgelPreput** [berenm/steam-cli#3]
After having installed Steam, and ran it (but never logged in through the GUI), there is a config.vdf file to read, but it has no 'Accounts' key. This will trigger a failure on line 276:

```python
          username = list(vdf.parse(f)['InstallConfigStore']['Software']['Valve']['Steam']['Accounts'].keys())[0]
```

If afterwards you remove the config.vdf file, or at least rename it to something else, the following crash occurs when running `steam-cli login`:

> Traceback (most recent call last):
>   File "/usr/bin/steam-cli", line 33, in <module>
>     sys.exit(load_entry_point('steam-cli==0.0.0', 'console_scripts', 'steam-cli')())
>   File "/usr/lib/python3.9/site-packages/steam_cli.py", line 765, in main
>     client.login()
>   File "/usr/lib/python3.9/site-packages/steam_cli.py", line 274, in login
>     if os.path.exists(cfg):
>   File "/usr/lib/python3.9/genericpath.py", line 19, in exists
>     os.stat(path)
> TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by amstelchen** [comment]
My `config.vdf` has the subkey `Steam` but written in _lowercase_, so when I use it like 

    username = list(vdf.parse(f)['InstallConfigStore']['Software']['Valve']['steam']['Accounts'].keys())[0]

there is at least no exception, but it will hang indefinitely on the login response from the Steam server.
